@baseUrl=http://localhost:8080

### Insert a vector
POST {{baseUrl}}/vectors
Content-Type: application/json

[0.1, 0.2, 0.3]

### Query for similar vectors
GET {{baseUrl}}/vectors/query?limit=3
Content-Type: application/json

[0.1, 0.3, 0.3]

### Find vector by ID
GET {{baseUrl}}/vectors/find-by-id/095bd5f0-ea2e-4527-942d-c251ad3505be

### Insert a random vector
POST {{baseUrl}}/vectors/random
